name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      run: |
        docker-compose build
        docker-compose push
    - name: Deploy to server
      run: |
        # Тут додайте команди для розгортання на вашому сервері